# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: HarmonyHu
brief-intro: 多思不如养志，多言不如守静，多才不如蓄德
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://harmonyhu.github.io" # the base hostname & protocol for your site

permalink: /:year/:month/:day/:title/

# other links
github_username:  HarmonyHu
email: harmonyhu@foxmail.com
weibo_username:
zhihu_username:

description_footer: HarmonyHu's Blog


# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: mathjax

# port
# port: 1234

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: <!--more-->

plugins:
  - jekyll-paginate

paginate: 6
